---
# https://github.com/istio/istio/blob/master/manifests/charts/istio-cni/values.yaml
profile: ambient

gobal:
  logAsJson: true
  defaultResources:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
