---
# https://raw.githubusercontent.com/longhorn/charts/master/charts/longhorn/values.yaml
persistence:
  defaultFsType: xfs
  defaultClassReplicaCount: ${default_replica_count}
defaultSettings:
  defaultReplicaCount: ${default_replica_count}
  createDefaultDiskLabeledNodes: true
  backupTarget: s3://homelab-longhorn-backup-${cluster_name}@us-east-2/
  backupTargetCredentialSecret: longhorn-s3-backup-credentials
csi:
  attacherReplicaCount: ${default_replica_count}
  provisionerReplicaCount: ${default_replica_count}
  resizerReplicaCount: ${default_replica_count}
  snapshotterReplicaCount: ${default_replica_count}
ingress:
  enabled: true
  ingressClassName: internal
  tls: true
  host: longhorn.${internal_domain}
metrics:
  serviceMonitor:
    enabled: true
