---
# https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-smartctl-exporter
serviceMonitor:
  enabled: true
  interval: 60s
  scrapeTimeout: 30s
tolerations:
  - effect: NoSchedule
    operator: Exists
