---
# https://raw.githubusercontent.com/stakater/Reloader/master/deployments/kubernetes/chart/reloader/values.yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/stakater/Reloader/master/deployments/kubernetes/chart/reloader/values.schema.json

reloader:
  podMonitor:
    enabled: true
  reloadStrategy: annotations
