---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: slow
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: ${storage_replica_count}
  fsType: xfs
  staleReplicaTimeout: "30"
  dataLocality: best-effort
  diskSelector: slow
  recurringJobSelectors: '[{"name": "filesystem-trim-daily", "isGroup": true}]'
