---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-heartbeat-ping-url
  annotations:
    # Pull-based replication from bootstrap-created secret in kube-system
    replicator.v1.mittwald.de/replicate-from: kube-system/heartbeat-ping-url
type: Opaque
data: {}
