---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-config.yaml
  - discord-secret.yaml
  - heartbeat-secret.yaml
  - alertmanager-route.yaml
  - alertmanager-canary.yaml
  - grafana-route.yaml
  - grafana-canary.yaml
  - prometheus-route.yaml
  - prometheus-canary.yaml
  - cert-manager-alerts.yaml
  - network-policy-alerts.yaml
  - external-secrets-alerts.yaml
  - grafana-alerts.yaml
  - loki-mixin-alerts.yaml
  - loki-mixin-recording-rules.yaml
