---
apiVersion: v1
kind: Secret
metadata:
  name: zipline-secret
  namespace: zipline
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: CORE_SECRET
    secret-generator.v1.mittwald.de/length: "32"
    secret-generator.v1.mittwald.de/encoding: base64
data: { }
