---
apiVersion: v1
kind: Secret
metadata:
  name: zipline-db-credentials
  namespace: zipline
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/encoding: base64
    secret-generator.v1.mittwald.de/length: "32"
type: kubernetes.io/basic-auth
stringData:
  username: zipline
