apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m
  path: kubernetes/platform
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: generated-cluster-vars
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
