---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lldap-secrets.yaml
  - oidc-certificate.yaml
  - internal-route.yaml
  - external-route.yaml
  - lldap-route.yaml
  - network-policy.yaml
  - namespace-labels.yaml
  - authelia-canary.yaml
  - prometheus-rules.yaml
