---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: authelia-default
  namespace: authelia
spec:
  description: "Allow Authelia + LLDAP: authentication portal with LDAP directory"
  endpointSelector: { }
  ingress:
    # Allow traffic from gateways (auth portal + LLDAP admin)
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: istio-gateway
      toPorts:
        - ports:
            - port: "9091"
              protocol: TCP
            - port: "17170"
              protocol: TCP
  egress:
    # Allow external HTTPS (OIDC discovery, WebAuthn attestation)
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
