---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/longhorn.io/recurringjob_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: &name snapshot-daily
spec:
  name: *name
  cron: "0 1 * * *"
  task: snapshot
  groups:
    - *name
  retain: 3
  concurrency: 5
  labels:
    jobname: *name
