---
apiVersion: v1
kind: Secret
metadata:
  name: lldap-secrets
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: "LLDAP_JWT_SECRET,LLDAP_LDAP_USER_PASS,LLDAP_KEY_SEED"
    secret-generator.v1.mittwald.de/length: "32"
    secret-generator.v1.mittwald.de/encoding: hex
stringData:
  LLDAP_JWT_SECRET: ""
  LLDAP_LDAP_USER_PASS: ""
  LLDAP_KEY_SEED: ""
