---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-db-password
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/length: "32"
    secret-generator.v1.mittwald.de/encoding: hex
    replicator.v1.mittwald.de/replicate-to: authelia
type: kubernetes.io/basic-auth
stringData:
  username: authelia_user
