---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-s3-backup-credentials
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: cnpg-s3-backup-credentials
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/cnpg-s3-backup/access-key-id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/cnpg-s3-backup/secret-access-key
