---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - superuser-secret.yaml
  - lldap-db-secret.yaml
  - authelia-db-secret.yaml
  - cluster.yaml
  - lldap-database.yaml
  - authelia-database.yaml
  - pooler.yaml
  - prometheus-rules.yaml
