---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - superuser-secret.yaml
  - backup-secret.yaml
  - cluster.yaml
  - scheduled-backup.yaml
  - pooler.yaml
  - prometheus-rules.yaml
