---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/canaries.flanksource.com/canary_v1.json
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: http-check-kromgo-external
spec:
  schedule: "@every 1m"
  http:
    - name: external-gateway-health
      url: https://kromgo.${external_domain}
      responseCodes: [200]
      maxSSLExpiry: 7
      thresholdMillis: 5000
