---
apiVersion: v1
kind: Secret
metadata:
  name: garage-admin-token
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: admin-token
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
data: { }
