---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage-admin
spec:
  parentRefs:
    - name: internal
      namespace: istio-gateway
  hostnames:
    - "garage.${internal_domain}"
  rules:
    - backendRefs:
        - name: garage-app
          port: 3903
