---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - admin-secret.yaml
  - garage-cluster.yaml
  - garage-s3-ingress.yaml
  - garage-route.yaml
  - garage-canary.yaml
  - prometheus-rules.yaml
  - network-policy.yaml
  - dragonfly-bucket.yaml
  - dragonfly-key.yaml
