---
apiVersion: v1
kind: Secret
metadata:
  name: garage-secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: rpc-secret
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
data: {}
