---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-superuser-replica
  namespace: authelia
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/cnpg-platform-superuser
type: Opaque
data: { }
