---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authelia-oidc-jwk
  namespace: authelia
spec:
  secretName: authelia-oidc-jwk
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
  commonName: authelia-oidc
  duration: 87600h    # 10 years
  renewBefore: 8760h  # 1 year
  privateKey:
    algorithm: RSA
    size: 4096
