---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: baseline-kube-api-access
spec:
  description: "Allow pods with kube-api access label to reach the Kubernetes API server"
  endpointSelector:
    matchExpressions:
      - key: io.cilium.k8s.namespace.labels.access\.network-policy\.homelab/kube-api
        operator: In
        values: ["true"]
  egress:
    # Allow access to Kubernetes API server
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
