---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dns-egress.yaml
  - prometheus-scrape.yaml
  - kube-api-access.yaml
  - health-probes.yaml
  - escape-hatch-allow-all.yaml
  - hbone-mesh.yaml
