---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: access-dragonfly-egress
spec:
  description: >-
    Allow namespaces with dragonfly access label to egress to Dragonfly in database namespace.
    Corresponding ingress rule is in the database namespace CNP.
    Usage: Add label access.network-policy.homelab/dragonfly=true to namespace.
  endpointSelector:
    matchExpressions:
      - key: io.cilium.k8s.namespace.labels.access.network-policy.homelab/dragonfly
        operator: In
        values: ["true"]
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: database
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
