apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal
spec:
  secretName: internal-tls
  issuerRef:
    name: ${tls_issuer:-cloudflare}
    kind: ClusterIssuer
  commonName: ${internal_domain}
  dnsNames:
    - ${internal_domain}
    - "*.${internal_domain}"
