---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/referencegrant_v1beta1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-tls-from-istio-gateway
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: istio-gateway
  to:
    - group: ""
      kind: Secret
      name: internal-tls
    - group: ""
      kind: Secret
      name: external-tls
