---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-config
  namespace: flux-system
spec:
  interval: 10m
  path: kubernetes/platform/bootstrap
  prune: true
  sourceRef:
    kind: ${source_kind}
    name: flux-system
    namespace: flux-system
