---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-labels.yaml
  - library-pvc.yaml
  - database-secret-replication.yaml
  - external-route.yaml
  - internal-route.yaml
  - canary.yaml
