apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secret-generator
spec:
  path: kubernetes/manifests/helm-release/secret-generator
  postBuild:
    substitute:
      HELM_CHART_VERSION: 3.4.1
