---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: istiod-
resources:
  - ../../common/resources/helm-release
configMapGenerator:
  - name: values
    behavior: replace
    files:
      - values.yaml
patches:
  - target:
      kind: HelmRelease
    patch: |-
      - op: replace
        path: /spec/chart/spec/chart
        value: istiod
      - op: add
        path: /spec/releaseName
        value: istiod
  - target:
      kind: HelmRepository
      name: app
    patch: |-
      - op: replace
        path: /spec/url
        value: https://istio-release.storage.googleapis.com/charts
