profile: ambient

gobal:
  logAsJson: true
  defaultResources:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

global:
  multiCluster:
    enabled: true
    clusterName: "${cluster_name}"
