---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-system.yaml
  - flux-system.yaml
  - monitoring.yaml
  - cert-manager.yaml
  - external-secrets.yaml
  - longhorn-system.yaml
  - istio-system.yaml
  - istio-gateway.yaml
  - database.yaml
  - garage.yaml
  - system.yaml
  - spegel.yaml
  - system-upgrade.yaml
  - kromgo.yaml
