---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database.yaml
  - database-dragonfly.yaml
  - garage.yaml
  - istio-gateway.yaml
  - kromgo.yaml
  - longhorn-system.yaml
  - monitoring.yaml
  - system-upgrade.yaml
