---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: system-upgrade-default
  namespace: system-upgrade
spec:
  description: "Allow Tuppr: Talos/Kubernetes upgrade controller requiring Talos API access"
  endpointSelector: { }
  ingress:
    # Allow Prometheus scraping
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    # Allow intra-namespace communication
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: system-upgrade
  egress:
    # Allow Kubernetes API access (watch TalosUpgrade/KubernetesUpgrade CRs, update node status)
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
    # Allow Talos API access to nodes (for executing upgrades)
    # Talos API runs on port 50000 on each node
    - toEntities:
        - host
      toPorts:
        - ports:
            - port: "50000"
              protocol: TCP
    # Allow intra-namespace communication
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: system-upgrade
