---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - password-secret.yaml
  - dragonfly-instance.yaml
  - network-policy.yaml
  - prometheus-rules.yaml
