---
apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-password
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/length: "32"
    secret-generator.v1.mittwald.de/encoding: base64
type: Opaque
data: { }
