---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-s3-backup-credentials
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: longhorn-s3-backup-credentials
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/longhorn-s3-backup/access-key-id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/longhorn-s3-backup/secret-access-key
