---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-ztunnel
spec:
  path: kubernetes/manifests/helm-release/istio-ztunnel
  postBuild:
    substitute:
      HELM_CHART_VERSION: 1.28.1
  dependsOn:
    - name: istio-base
    - name: istiod
    - name: istio-cni
