---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - ../../../manifests/common/resources/namespace
  - istio-base.yaml
  - istiod.yaml
  #- istio-cni.yaml
  #- istio-ztunnel.yaml
