---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - internal-gateway.yaml
  - external-gateway.yaml
  - coraza-wasm-plugin.yaml
  - coraza-config.yaml
  - coraza-waf-rules.yaml
  - network-policy.yaml
