---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/canaries.flanksource.com/canary_v1.json
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: http-check-hubble
spec:
  schedule: "@every 1m"
  http:
    - name: hubble-gateway-health
      url: https://hubble.${internal_domain}
      responseCodes: [200]
      maxSSLExpiry: 7
      thresholdMillis: 5000
